@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant LoginController
participant LoginUseCase
participant LoginEntity
participant LoginDatabase

LoginController -> LoginUseCase: execute()
LoginUseCase -> LoginUseCase: validate()
LoginUseCase -> LoginDatabase: fetchUserData()
LoginDatabase --> LoginUseCase: userData
LoginUseCase -> LoginUseCase: process()
LoginUseCase --> LoginController: response

@enduml


