@startuml
'https://plantuml.com/sequence-diagram

autonumber

User -> SavePreferencesController: Selects Save Preferences
SavePreferencesController -> SavePreferencesInteractor: execute()
participant Entity
SavePreferencesInteractor -> Database: save()

SavePreferencesInteractor <-- Database: userPreferences
User <-- SavePreferencesInteractor: Displays conformation message
@enduml